[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["env -u NPM_CONFIG_PRODUCTION npm ci --include=dev"]

[phases.build]
cmds = ["npm run railway:build"]

[start]
cmd = "node dist/daemon/qflushd.js"
