[phases.setup]
nixPkgs = ["nodejs", "dotnet-sdk"]

[phases.install]
cmds = ["npm ci --include=dev", "dotnet restore || true"]

[phases.build]
cmds = ["npm run railway:build"]

[start]
cmd = "npm run railway:start"
